# Generated by Django 3.2.12 on 2022-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectC', '0002_auto_20220412_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePic',
        ),
    ]
