# Generated by Django 4.0.3 on 2022-05-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectC', '0003_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavior',
            name='sign',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
