# Generated by Django 4.0.4 on 2022-04-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectC', '0003_remove_user_profilepic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
